name:                brick-tac-toe
version:             0.1.0.0

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -threaded
  dependencies:
    - brick
    - text
    - microlens
    - microlens-th
    - vty
    - vector
    - safe
    - text-zipper
    - network
    - bytestring
    
executables:
  client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brick-tac-toe

  server:
    main:               Main.hs
    source-dirs:        server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - bytestring
      - network

# tests:
#   brick-tac-toe-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - brick-tac-toe
